In [5]:
import torch
from datasets import *

X = torch.tensor([[1,0,1], [1,1,1]]).float()
y = torch.tensor([[1], [2]]).float()

loader = FastTensorDataLoader(X, y, batch_size=1, shuffle=True)

In [6]:
for i in range(10):
    for x, Y in loader:
        print(x, Y)

tensor([[1., 0., 1.]]) tensor([[1.]])
tensor([[1., 1., 1.]]) tensor([[2.]])
tensor([[1., 0., 1.]]) tensor([[1.]])
tensor([[1., 1., 1.]]) tensor([[2.]])
tensor([[1., 1., 1.]]) tensor([[2.]])
tensor([[1., 0., 1.]]) tensor([[1.]])
tensor([[1., 1., 1.]]) tensor([[2.]])
tensor([[1., 0., 1.]]) tensor([[1.]])
tensor([[1., 0., 1.]]) tensor([[1.]])
tensor([[1., 1., 1.]]) tensor([[2.]])
tensor([[1., 0., 1.]]) tensor([[1.]])
tensor([[1., 1., 1.]]) tensor([[2.]])
tensor([[1., 0., 1.]]) tensor([[1.]])
tensor([[1., 1., 1.]]) tensor([[2.]])
tensor([[1., 1., 1.]]) tensor([[2.]])
tensor([[1., 0., 1.]]) tensor([[1.]])
tensor([[1., 1., 1.]]) tensor([[2.]])
tensor([[1., 0., 1.]]) tensor([[1.]])
tensor([[1., 1., 1.]]) tensor([[2.]])
tensor([[1., 0., 1.]]) tensor([[1.]])
